// <auto-generated />
using Infrastructure.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(LegoContext))]
    [Migration("20220523104647_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.LegoProduct", b =>
                {
                    b.Property<string>("ProductID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductStatusID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.ToTable("LegoProducts");
                });

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.LegoProductStatus", b =>
                {
                    b.Property<int>("ProductStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductStatusID"), 1L, 1);

                    b.Property<string>("ProductStatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProductStatusID");

                    b.ToTable("LegoProductStatuses");
                });

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.LegoProductTheme", b =>
                {
                    b.Property<string>("ProductThemeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.HasKey("ProductThemeID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ThemeID");

                    b.ToTable("LegoProductThemes");
                });

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.Theme", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThemeID"), 1L, 1);

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ThemeID");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.LegoProductTheme", b =>
                {
                    b.HasOne("Infrastructure.DataAccess.Entities.LegoProduct", "Product")
                        .WithMany("ProductThemes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.DataAccess.Entities.Theme", "Theme")
                        .WithMany("ProductThemes")
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.LegoProduct", b =>
                {
                    b.Navigation("ProductThemes");
                });

            modelBuilder.Entity("Infrastructure.DataAccess.Entities.Theme", b =>
                {
                    b.Navigation("ProductThemes");
                });
#pragma warning restore 612, 618
        }
    }
}
